spring:
  datasource:
    url: jdbc:mysql://xx:3306/xx?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: xx
    password: xx
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 400MB

  # 静态资源
  resources:
    static-locations: classpath:web/
  application:
    name: zxyx

mybatis:
  type-aliases-package: cn.zhaoxi.zxyx.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8080

logging:
  level:
    root: info
  file:
    path: /home/zxyx_project/log/
    name: photo.log

# 此地址由nginx代理，即前端访问http://localhost/rss/ 指向 rss-path
rss-path:
  linuxPath: /home/ossfs/