spring:
  datasource:
    url: jdbc:mysql://xx:3306/xx?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: xx
    password: xx
    driver-class-name: com.mysql.jdbc.Driver

  # 静态资源
  resources:
    static-locations: classpath:web/
  application:
    name: zxyx

server:
  port: 8080

logging:
  level:
    root: info
  file:
    path: /home/zxyx_project/log/
    name: photo.log